### ISSUE TITLE
Selected localities should be preserved when changing settings

### ISSUE THREAD

**Issue by davidebbo** [davidbau/covid-19-chart#1]
With the exception of a Domain change, changing settings does not affect the legend. So ideally, changing non-Domain settings should not reset the legend selection.

i.e. I should be able to select US & France, and then tweak things like scale, start, confirmed/death, etc... without losing my country selection.

**Comment by davidbau** [comment]
Totally agreed.  Implementation notes.
* Currently the selection state is dealt with by chartist.js and not connected to vue.js's application state.  This can and should be fixed.
* If we also add it to the vue route, then you would be able to print or email a matching state.

Design puzzle:
* What to do when changing Intl/Us or confirmed/deaths and the active states change?  Should we remember the active things anyway, or should we memory of ones that no longer apply?  Maybe they should be remembered in the state but should not be put into the route?

**Comment by davidbau** [comment]
Here's a proposed design:
* When there are no remembered selected localities (the default), everything is shown.
* Once something is selected, remember the set across plot changes, even when the locality goes invisible.  If the plot is changed to make it visible again, it's selected again.
* But there is zero overlap between selected localities and visible things in the plot, then discard the remembered set at that time.  So it goes back to everything-shown.

**Comment by davidebbo** [comment]
Yes, that sounds reasonable. BTW, if you're not already on it, I could give it a shot, though I'm sure it would take me longer than you as I have very little client side JS experience (and don't know the code). But happy to try (and possibly bail)!

**Comment by davidbau** [comment]
Ooh so cool!   Yeah, if you'd like to give it a shot, please do!

If you decide not to in the end, that's totally OK too.  Happy to answer
any questions about the (underdocuented) code.  But if you haven't used
vue.js before, it might be a good chance to see how it works and how it
compares with other things :-).

**Comment by davidebbo** [comment]
Ok, I'll give it a shot over the weekend.

**Comment by davidebbo** [comment]
Taking a look, this does seem harder than I anticipated :)

- There seems to be no external visibility on the current selection state of the legend plugin. It's all managed privately inside the plugin. I now see that's what you meant by "Currently the selection state is dealt with by chartist.js and not connected to vue.js's application state".
- There is no obvious way of setting the selected state when initializing the plugin: https://github.com/CodeYellowBV/chartist-plugin-legend/issues/62.

Does the plugin support connecting the selection state to vue's application state? That would potentially take care of both issues, but I don't see how to do that from looking at the plugin's code and doc.

**Comment by davidbau** [comment]
Yeah, so the chart is not a vue component but just glued in.

In time-honored JS tradition, when the encapsulation isn't done the way we need, we copy the code and hack on it.  Fortunately the code we need to hack is not too bad.  There are centralized ways to get data into and out of the legend plugin.

To get data in (i.e., to set the initial legend state when the chart is rebuilt), they pass it all the arguments through an "options" object whose defaults are here, and which is passed in here.
https://github.com/davidbau/covid-19-chart/blob/master/lib/chartist-plugin-legend.js#L23-L29
https://github.com/davidbau/covid-19-chart/blob/f4e1fd37e5a849c312485e7451a0b3b343e77fde/index.html#L606

We need a new option that initializes state so it's not always just "true" at the start
https://github.com/davidbau/covid-19-chart/blob/master/lib/chartist-plugin-legend.js#L228

To get data out, there is already an unused "onClick" event that we don't currently use
https://github.com/davidbau/covid-19-chart/blob/master/lib/chartist-plugin-legend.js#L196-L198

Currently it just passes a useless event object in the callback, so it probably needs to change to be more useful.  We could change that callback to instead (or in addition) pass something helpful like the current "legends" array or some object derived from it.  (It might be pretty and symmetric for the state object to have exactly the same format we want to use for passing in to the option at initialization.)

Then in our app, argument(s) will have to be added to plot_series to let the initial legend state and callback be hooked up
https://github.com/davidbau/covid-19-chart/blob/f4e1fd37e5a849c312485e7451a0b3b343e77fde/index.html#L677
https://github.com/davidbau/covid-19-chart/blob/f4e1fd37e5a849c312485e7451a0b3b343e77fde/index.html#L541
https://github.com/davidbau/covid-19-chart/blob/f4e1fd37e5a849c312485e7451a0b3b343e77fde/index.html#L606

And since we want to load+save the legend view state on the url, we can add a computed Vue property like this:

https://github.com/davidbau/covid-19-chart/blob/f4e1fd37e5a849c312485e7451a0b3b343e77fde/index.html#L656

Note that once the property is set up, as soon as you change the url, it should rebuild the chart.  Maybe call the property "view" and format it as a semicolon-separated list of legend labels or something like that.

If we want the chart to be automatically rebuilt when the url changes we can tell vue to redraw it here:
https://github.com/davidbau/covid-19-chart/blob/f4e1fd37e5a849c312485e7451a0b3b343e77fde/index.html#L664
But we might not want that because it will cause flashing when we change the property in the onclick (unless we add some "if (not inside the onclick)")

**Comment by davidebbo** [comment]
Yes, if we're ok hacking on chart/legend, that definitely opens up possibilities. Thanks for the pointers, I'll take. a crack at it!

Note that today, the legend selection state is not captured in the  URL, so technically that is a slightly separate issue. Though I agree it would be nice to fix that as well, so you can share a URL that specifically compares a subset of locations.

**Comment by davidebbo** [comment]
Fixed in 090740d07bda2c78620586a36a5db9515c8c1547.

**Comment by davidbau** [comment]
PR #8 fixes this - thanks David!

My kids noticed a related issue, opened as #9.
