### ISSUE TITLE
Colors should stay consistent when changing views.

### ISSUE THREAD

**Issue by davidbau** [davidbau/covid-19-chart#9]
A bit confusing for colors to switch around when the same localities appear in different views - the graph would be more useful if colors were stable.

We should add some state to track colors and minimize color changes where possible.

**Comment by davidebbo** [comment]
That probably relates to the fact that the set of locations can change with different views. e.g. GA shows up by default under Death but not Confirmed, I assume because it's only showing the top 10 for each.

That makes it a tricky problem, since we only have 15 colors and we can't predict which locations will fall off as we change view.

Crazy idea: instead of a fixed set of colors, hash the location name and get a stable color from that. It would technically work, but it's not great because some colors may end up being too similar (or even identical).

**Comment by davidbau** [comment]
I like your crazy idea, esp now that you're programmatically generating the palette!

**Comment by davidebbo** [comment]
I'll try to work on that or some variant of it.

**Comment by davidebbo** [comment]
The hard part is to do this without having to change chartist. It's always going to use the same css styles (ct-series-a, b, c, ...), and since it's not always working with the same locations, it's hard to be color-stable.

The only way I can think of doing this is to regenerate the dynamic styles on each view change. This way, we can drive the colors used by chartist/legend without needing to touch their css class selection logic. Not sure if that would be considered css abuse...

Any other options?

**Comment by davidbau** [comment]
CSS doesn't care if it's abused or not :-).  Now that you have stylesheet
generation code, maybe we should just use it!

**Comment by davidbau** [comment]
Changing chartist is also OK.

(Also, my viz friends ask me why I'm using this oddball charting library instead of charting with D3 or plotly or something more widespread.)

**Comment by davidebbo** [comment]
I've never really done HTML/frontend development, so I'm not familiar with any of those :)

Thinking about it some more, what I suggest above would not be fully correct with more than 26 locations, because it will end up always using the same color for the 27th and for the 1st (and 28th/2nd, etc...), and that will not be stable as the list gets a different set of locations when the view changes.

So I need to think about it some more before adding a bunch of hacks that don't completely solve it...

**Comment by davidbau** [comment]
Thanks for the pull request...
But after playing with it, I don't think this is the right solution in the end.

Now that I see the alternative, I realize how much aesthetic value we were getting out of chartist.js's default pretty rainbow of distinct but compatible colors.
![image](https://user-images.githubusercontent.com/3458792/77839826-65f27e00-714e-11ea-86c6-a3b8f22ac632.png)
This second row is much more pleasing and clear (it is analogous to alphabetizing the colors).
![image](https://user-images.githubusercontent.com/3458792/77839845-8d494b00-714e-11ea-9595-36a036d3aa5e.png)
Ideally we'd preserve that pretty rainbow or another palette that is chosen on the basis of color aesthetics and clarity.

I have been thinking a while to see if there is a good solution, but I don't have one to suggest.  There are several conflicting needs.
(1) Initial graph should be as pleasing and clear as possible, so the current fixed palette achieves this.  Notice that the current color assignments have a few other properties - the clearest colors are at the start of the palette, with the less-distinctive colors later in the palette.  Currently by assigning the largest-number-cases to the start of the palette it makes it easiest to see the most important lines.
(2) But then when views are switched the colors of a locality should stay the same.
(3) And also when a link is bookmarked, printed, or emailed, the colors should stay the same.
(4) Final graph that you bookmark and come back to should be as clear and pretty as possible.

I don't think it's simple to do all three at once.  Currently we do (1) and (3) and (4) but not (2).  The current CL does (2) and (3) but not (1) or (4), but I after playing with it I don't think that is the right trade-off.

I was going to suggest a more complex solution that does (1) and (2) but not (3) or (4), but then I'm not sure that's the right trade-off either.  So still no specific design suggestion from me.  Probably doing all (1) and (2) and (3) is complex, and then would sacrifice (4), and I don't know how that would look (maybe it would be OK).

Also, minor issue - the counties (like King County WA) - are not covered by the current code, and they don't get legend CSS.
![image](https://user-images.githubusercontent.com/3458792/77839807-4d826380-714e-11ea-9a2e-ddca689af455.png)

**Comment by davidebbo** [comment]
Oh, I didn't even know there was county support! Is the only way to use that to search for them by name? It seems a bit quirky as it happens on top of either Intl or US. Might need some improved UI here, but that's a separate discussion.

One note is that the current code doesn't really do (3), because if you come back the next day, the colors could change based on new data. So it's only stable for up to a day or so. Do you agree? I don't think it's a huge deal though.

I can think of a tweak to my change that would mostly do (1), (2) and (3): perform color assignment based on the ordered data instead of alphabetically. The small catch is that we'd need to pick one series for each domain (e.g. confirmed totals), and then that coloring would be used for other series in the same domain (e.g. deaths total). My take is that this will be close enough, because the data ordering across series is high correlated. So it'll mostly be the same colors, but with a few exceptions that go a bit further down the color list.

What do yo think?

**Comment by davidbau** [comment]
Currently the color assignment is already based on the ordered data, so
maybe that's why it already feels not-too-bad!

**Comment by davidebbo** [comment]
Yes, it's based on the ordered data for each given series, which is why it's not stable. What I'm suggesting is to use the ordered data from one main series across the other series, giving us both stability and nice colors (but with the small color caveat above). If you think that's potentially interesting, I'll give it a try.

**Comment by davidbau** [comment]
Oh cool, that makes a lot of sense, e.g., ordering always based on score
based on total confirmed cases., I understand.

There will still be instability when some state comes into or out of the
top-10, though - so I don't know if the improvement will be enough to be
noticeable.

The brute-force less-elegant solution would be to directly remember and
recall {locality -> visible index} before and after a view change, and to
just choose the ordering among the visible items to reuse indexes when
possible.  Less elegant because there might not be a clean way to do the
pluming to remember and discard this state at the right time.

**Comment by davidebbo** [comment]
> There will still be instability when some state comes into or out of the top-10, though

I want to make sure I understand this comment. Are you referring to instability from day to day as the data changes and the total confirmed cases get reordered? I was mostly trying to solve color stability per locality **within one session as you change series**, and not **a locality will forever have the same color**.

I think what I'm proposing fixes the former 100%. Fixing the latter would probably require hard coding locality to color mapping for the top localities, making them stable even if they trade place from day to day. Not sure we want to go there though.

**Comment by davidbau** [comment]
In this comment I'm not talking about stability within one session, not
day-to-day.  But I'm probably misunderstanding your solution.  Here's a
concrete setting that we can talk about.

For the example, let's say we're showing "top 3" instead of "top 10".
Today the top three countries (outside China) by total cumulative confirmed
are (1) US (2) Italy (3) Spain.  But top three countries by day-to-day
delta in confirmed are (1) US (2) Spain (3) Germany.  What colors to
assign?  And then suppose the user selects three counties (1) King, WA (2)
Snohomish, WA (3) Sussex, MA.

I had imagined that to use colors, A, B, C in both cases we would want to
find an algorithm that assigns US-A, Italy-B, Spain-C and then, when
flipping views, the same for US and Spain but then Germany-B.  But then
when switching to the counties, there is no overlap so then it's just
King-A Snohomish-B, Sussex C again.  But achieving this would seem to
require keeping a bunch of extra state, probably messy.

Can you describe what your method would answer when switching between the
three views?

**Comment by davidebbo** [comment]
What I'm suggesting is:

- The entire list of countries would be assigned a color, using the confirmed totals data ordering.
- That assignment would then be used throughout

So in your example, we'd have { US: red, Italy: orange, Spain: yellow, Germany: brown }. So when looking at top 3 deltas, orange would simply not be used since it belongs to Italy. You'd have red, yellow, brown.

The reasoning is that the ordering between series is similar enough that even if we end up skipping a few colors, we're still mostly using 'top' colors and it will look ok.

Clearly, if you think it's higher priority to always use the very top colors for all graphs, then this is not a good option.

The scheme you are suggesting is potentially interesting as well. Partial stability while always using the best colors. But yeah, the implementation looks tricky, and I think some sequences of series transitions could lead to odd results, where you can end up circling back to your original series and have different colors than you started with.

I need to look more into how counties work. Seems they are not their own domain, and they can be added to both Intl and US graphs?

Who new this could be such a tricky problem? :)

**Comment by davidbau** [comment]
Cool, yeah.  To explaiin "domains" - it has evolved in a way that the
different "domains" is a bit of a user interface illusion.  Actually any
locality (country, US state, or county) can be mixed on the same graph.
The "domain" is just used to choose an automatic set of "top 10" if you
haven't selected specific localities.  And "top" is set to zero by default
as soon as you add some localities (in advanced mode you can increase top
and mix both together).

I'm thinking that the main use-case for this chart (as distinct from what
you can get just opening the financial times) will be to let people put
together hyperlocal visualizations that plot their local situation against
historical and international histories, to try to rate whether their own
suburban town is doing "as well as S Korea" or "as badly as Italy." - so
having the colors look good for this case is a key case for me.

**Comment by davidebbo** [comment]
Yep, got it on the domains/locality behavior (I concluded the same by playing around with it).

I'm warming up to your flavor of the proposal. Here is how I would state it:

- If a locality in the current graph existed in the previous graph, reuse the color that it had in the previous graph
- Otherwise, assign the best color index that was not consumed by the previous rule

So we only keep some state from one render to the next, and not long term. There is some logic, but it's probably not terribly complicated.

How does that sound? If you think it has wings, I can give it a try, if only so we can see what it feels like in practice.

**Comment by davidebbo** [comment]
And to state one clear drawback of this approach: sharing a link, or even just refreshing the page will in some cases change the colors because we won't have the previous state. Unless we start saving the previous color state on the query string, but that starts getting complicated!

**Comment by davidbau** [comment]
Good points...

Refreshing is a similar code path as emailing and printing (it flips on
bare mode and white backgrounds, then prints) - so and today printing "just
works" with the colors seen. Making it unsurprising is probably too complex
to be worth it...

Maybe it's ok if printing and emailing is a color surprise?

Maybe its ok enough to try it - stable-color printing would be fixable with
more url params if it actually needs to be fixed.  Probably in most
situations the change will not be noticed.

**Comment by davidebbo** [comment]
Alright, give #24 a try.

Probably spending too much time on this color problem, but hey, I'm stuck at home on the weekend, so I have time :)

**Comment by davidebbo** [comment]
Ok, so here is the deal on the color stability saga. So we still want the same basic thing, as per above:

- If a locality in the current graph existed in the previous graph, reuse the color that it had in the previous graph
- Otherwise, assign the best color index that was not consumed by the previous rule

But there are two completely different way of achieving this (without changing chartist):

1. Current solution: reorder the css styles to match the series
2. Alternate: reorder the series to match the css styles!

The pros for (2) are:

- We don't need to dynamically mess with css styles, which frankly was a nasty hack
- It avoid the flashing resulting from that hack
- It keeps the legend itself much more stables. The color ordering in the legend never change, and the locality assigned to them only change when necessary. That feels a lot cleaner to me!

The cons is that the legend is no longer ordered based on the data, but I don't think that's a big deal.

Before looking at the code details, I suggest just playing around with it to see how it feels (it's #27).

**Comment by davidbau** [comment]
Hey, it feels pretty good!  I agree, I don't notice the different order at
all!

>

**Comment by davidbau** [comment]
This works really well now.  Thank you @davidebbo!
